/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package wuit.application.wins;

import java.awt.AWTEvent;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.WindowEvent;
import java.awt.Font;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import wuit.common.crawler.composite.DSComposite;
import wuit.common.crawler.composite.DSExtractor;
import wuit.common.doc.xml.ParseWorkConfigXml;
import wuit.crawler.main.MainServer;

/**
 *
 * @author lxl
 */
public class CrawlersMain extends javax.swing.JFrame {

    /**
     * Creates new form CrawlersMain
     */
    public CrawlersMain() {
        initComponents();
        this.setLocation(300,100);
        jList1.setListData(listVals);
        
        String[] header = { "名称", "值" }; //定义表头
        DefaultTableModel model=new DefaultTableModel(header,0);
        model.setColumnCount(2);
        model.setRowCount(1);
//        jTable1.setModel(model);
//        jTable1.getTableHeader().setFont(new Font("Dialog", 0, 14)); 
        
        String[] header2 = { "状态项名称", "值" }; //定义表头
        DefaultTableModel mode2=new DefaultTableModel(header2,0);
        mode2.setColumnCount(2);
        mode2.setRowCount(1);        
        
        jTable2.setModel(mode2);
        jTable2.getTableHeader().setFont(new Font("Dialog", 0, 14));        
        
        
        jTabbedPane1.setTitleAt(0, "运行状态");
        jTabbedPane1.setTitleAt(4, "运行状态");
        
        jTabbedPane1.setTitleAt(1, "直接获取地址"); 
        String[] header3 = { "序号","标签","名称","地址","省","地市","县区","路","号","镇","村","大楼","楼层","户号","参照","状态"}; //定义表头
        mode3 = new DefaultTableModel(header3,0);
        mode3.setColumnCount(16);
//        mode3.setRowCount(1);
        
        jTable3.setModel(mode3);
        jTable3.getTableHeader().setFont(new Font("Dialog", 0, 14));

        jTabbedPane1.setTitleAt(2, "无省市县"); 
        String[] header4 = { "序号","标签","名称","地址","省","地市","县区","路","号","镇","村","大楼","楼层","户号","参照","状态"}; //定义表头
        mode4 = new DefaultTableModel(header4,0);
        mode4.setColumnCount(16);
//        mode3.setRowCount(1);
        
        jTable4.setModel(mode4);
        jTable4.getTableHeader().setFont(new Font("Dialog", 0, 14));

        jTabbedPane1.setTitleAt(3, "有歧义的地址"); 
        String[] header5 = { "序号","标签","名称","地址","省","地市","县区","路","号","镇","村","大楼","楼层","户号","参照","状态"}; //定义表头
        mode5 = new DefaultTableModel(header5,0);
        mode5.setColumnCount(16);
//        mode3.setRowCount(1);
        
        jTable5.setModel(mode5);
        jTable5.getTableHeader().setFont(new Font("Dialog", 0, 14));
        
        
       // mode3.addRow(new String[]{"标签","名称","省","地市","县区","路","号","镇","村","大楼","楼层","户号"});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTxtCrawlers = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtUrlSum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtUrls = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtPageSum = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtPages = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxtItemSum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtItems = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButtonStart = new javax.swing.JButton();
        jButtonInterupter = new javax.swing.JButton();
        jButtonContinue = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jButtonOutput = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();

        jPanel1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 100));

        jButton1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jButton1.setText("浏览配置");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jTabbedPane1.addTab("tab1", jScrollPane3);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jTabbedPane1.addTab("tab2", jScrollPane4);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable4);

        jTabbedPane1.addTab("tab3", jScrollPane5);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable5);

        jTabbedPane1.addTab("tab4", jScrollPane6);

        jPanel9.setLayout(new java.awt.GridLayout(1, 2));

        jPanel10.setLayout(new java.awt.GridLayout(4, 3));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("爬虫数");
        jPanel10.add(jLabel3);

        jTxtCrawlers.setMinimumSize(new java.awt.Dimension(30, 30));
        jTxtCrawlers.setPreferredSize(new java.awt.Dimension(30, 21));
        jPanel10.add(jTxtCrawlers);
        jPanel10.add(jLabel10);
        jPanel10.add(jLabel9);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("待爬链接数");
        jPanel10.add(jLabel2);

        jTxtUrlSum.setPreferredSize(new java.awt.Dimension(30, 21));
        jPanel10.add(jTxtUrlSum);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("已完成数");
        jPanel10.add(jLabel5);

        jTxtUrls.setMinimumSize(new java.awt.Dimension(30, 21));
        jPanel10.add(jTxtUrls);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("需要处理网页");
        jPanel10.add(jLabel6);
        jPanel10.add(jTxtPageSum);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("已处理网页");
        jPanel10.add(jLabel7);

        jTxtPages.setMinimumSize(new java.awt.Dimension(30, 21));
        jTxtPages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPagesActionPerformed(evt);
            }
        });
        jPanel10.add(jTxtPages);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("待处理记录数");
        jPanel10.add(jLabel8);

        jTxtItemSum.setMinimumSize(new java.awt.Dimension(30, 21));
        jPanel10.add(jTxtItemSum);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("已完成数");
        jPanel10.add(jLabel4);

        jTxtItems.setMinimumSize(new java.awt.Dimension(30, 21));
        jPanel10.add(jTxtItems);

        jPanel9.add(jPanel10);

        jPanel11.setLayout(new java.awt.GridLayout(4, 1));
        jPanel11.add(jLabel11);
        jPanel11.add(jProgressBar1);
        jPanel11.add(jProgressBar2);
        jPanel11.add(jProgressBar3);

        jPanel9.add(jPanel11);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab5", jPanel7);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1)
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("运行状态");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 409, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel5.setPreferredSize(new java.awt.Dimension(811, 60));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel18.setText("jLabel18");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel1.setText("互联网位置服务信息采集");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(721, 400));

        jPanel6.setMaximumSize(new java.awt.Dimension(327, 327));
        jPanel6.setPreferredSize(new java.awt.Dimension(280, 25));

        jButtonStart.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jButtonStart.setText("开始");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jButtonInterupter.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jButtonInterupter.setText("中断");

        jButtonContinue.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jButtonContinue.setText("继续");

        jButtonStop.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jButtonStop.setText("终止");
        jButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopActionPerformed(evt);
            }
        });

        jButtonOutput.setText("输出结果");
        jButtonOutput.setName(""); // NOI18N
        jButtonOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOutputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jButtonStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonInterupter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonContinue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonStop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOutput)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonStart)
                .addComponent(jButtonInterupter)
                .addComponent(jButtonContinue)
                .addComponent(jButtonStop)
                .addComponent(jButtonOutput))
        );

        jPanel8.setPreferredSize(new java.awt.Dimension(204, 201));
        jPanel8.setLayout(new java.awt.GridLayout(3, 4));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("爬虫数");
        jPanel8.add(jLabel12);
        jPanel8.add(jTextField1);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("当前活动数");
        jPanel8.add(jLabel13);
        jPanel8.add(jTextField2);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("搜索深度");
        jPanel8.add(jLabel14);
        jPanel8.add(jTextField3);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("搜索模式");
        jPanel8.add(jLabel15);
        jPanel8.add(jTextField4);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("关键字/链接");
        jPanel8.add(jLabel16);
        jPanel8.add(jTextField5);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("链接过滤");
        jPanel8.add(jLabel17);
        jPanel8.add(jTextField6);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("信息提取单元数");
        jPanel8.add(jLabel19);
        jPanel8.add(jTextField7);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("网页匹配模板库");
        jPanel8.add(jLabel20);

        jTextField8.setToolTipText("");
        jPanel8.add(jTextField8);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("默认匹配模板");
        jPanel8.add(jLabel21);
        jPanel8.add(jTextField9);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("网页清理规则库");
        jPanel8.add(jLabel22);
        jPanel8.add(jTextField10);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("jLabel23");
        jPanel8.add(jLabel23);
        jPanel8.add(jTextField11);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("jLabel24");
        jPanel8.add(jLabel24);
        jPanel8.add(jTextField12);

        jLabel25.setText("jLabel25");
        jPanel8.add(jLabel25);

        jTextField13.setText("jTextField13");
        jPanel8.add(jTextField13);

        jLabel26.setText("jLabel26");
        jPanel8.add(jLabel26);

        jTextField14.setText("jTextField14");
        jPanel8.add(jTextField14);

        jLabel27.setText("jLabel27");
        jPanel8.add(jLabel27);

        jTextField15.setText("jTextField15");
        jPanel8.add(jTextField15);

        jLabel28.setText("jLabel28");
        jPanel8.add(jLabel28);

        jTextField16.setText("jTextField16");
        jPanel8.add(jTextField16);

        jLabel29.setText("jLabel29");
        jPanel8.add(jLabel29);

        jTextField17.setText("jTextField17");
        jPanel8.add(jTextField17);

        jLabel30.setText("jLabel30");
        jPanel8.add(jLabel30);

        jTextField18.setText("jTextField18");
        jPanel8.add(jTextField18);

        jLabel31.setText("jLabel31");
        jPanel8.add(jLabel31);

        jTextField19.setText("jTextField19");
        jPanel8.add(jTextField19);

        jLabel32.setText("jLabel32");
        jPanel8.add(jLabel32);

        jTextField20.setText("jTextField20");
        jPanel8.add(jTextField20);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      JFileChooser file = new JFileChooser (".");
      file.setAcceptAllFileFilterUsed(false);
      
      int result = file.showOpenDialog(null);  
      if(result == JFileChooser.APPROVE_OPTION){
          String path = file.getSelectedFile().getAbsolutePath();          
          config = new ParseWorkConfigXml();
          config.parseWorks(path);
          
         params = config.getWorksParams();
         for (int i=0;i<params.size();i++){
              listVals.add(params.get(i).title);
          }
          jList1.setListData(listVals);
      }      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        String str=(String)this.jList1.getSelectedValue(); 
        int index = this.jList1.getSelectedIndex();
        String[] header = { "名称", "值" }; //定义表头
        DefaultTableModel model=new DefaultTableModel(header,0);//用表头生成一个DefaultTableModel 对象
        
        
        //多行数据，循环下面两行代码      
        if(  null != params && -1 != index){
            currJobIndex = index;
            DSExtractor extractor = params.get(index);
            model.addRow(new String[]{"模式",extractor.crawlerMode+""});
            model.addRow(new String[]{"保存目录",extractor.outPath+""});
            model.addRow(new String[]{"URL",extractor.CrawlerUrl});
            model.addRow(new String[]{"搜索深度",extractor.crawlerDeepth+""});
            model.addRow(new String[]{"并发数",extractor.task+""});
            for(int i=0;i<extractor.crawlerKeyWords.size();i++){
                model.addRow(new String[]{"关键字" + i,extractor.crawlerKeyWords.get(i)});
            }
            
//            jTable1.setModel(model);//把model作为JTable的数据来源
        }        
    }//GEN-LAST:event_jList1MouseClicked

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        // TODO add your handling code here:
        /*
        jButtonStart.setVisible(false);
        jButtonStop.setVisible(true);;
        
        if(currJobIndex == -1)
            return;
        if(params == null)
            return;
        if (server == null)
            server =  new MainServer();
        
        server.Initialize(params.get(currJobIndex));
        server.start(); 
        disp.start();
        */
        MainCrawler crawler = new MainCrawler();
        new Thread(crawler).start();
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopActionPerformed
        // TODO add your handling code here:
        
        server.stopCrawling();
        disp.display();
    }//GEN-LAST:event_jButtonStopActionPerformed

    private void jButtonOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOutputActionPerformed
        // TODO add your handling code here:
        Output query = new Output();
        new Thread(query).start();
    }//GEN-LAST:event_jButtonOutputActionPerformed

    int index=0;
    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        if (index!=jTabbedPane1.getSelectedIndex()){
        //    if(index== jTabbedPane1.setEnabledAt(index+1,true);
        }
        index = jTabbedPane1.getSelectedIndex();
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jTxtPagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPagesActionPerformed

    class MainCrawler implements Runnable{
        public MainCrawler(){
        }
        
        public void run(){
            jButtonStart.setVisible(false);
            jButtonStop.setVisible(true);;

            if(currJobIndex == -1)
                return;
            if(params == null)
                return;
            if (server == null)
                server =  new MainServer();

//            server.Initialize(params.get(currJobIndex));
//            server.start(); 
            new Thread(disp).start();
        }        
    }
    
    
    class Output implements Runnable{
        public Output(){
        }
        
        public void run(){
            try {
                //jTable3.getModel().getModel.removeAll();
                while(mode3.getRowCount()>0){
                    mode3.removeRow(0);
                }
                Thread.sleep(10);
                while(mode4.getRowCount()>0){
                    mode4.removeRow(0);
                }
                Thread.sleep(10);
                while(mode5.getRowCount()>0){
                    mode5.removeRow(0);
                }
                Thread.sleep(10);
                int count = 1;
                dispInfo(MainServer.DBCrawler.listDSCompositesDrct,"listDSCompositesDrct",count,mode3);
                Thread.sleep(10);
                dispInfo(MainServer.DBCrawler.listDSCompositesDrct,"listDSCompositesNull",count,mode4);
                Thread.sleep(10);
                dispInfo(MainServer.DBCrawler.listDSCompositesDrct,"listDSCompositesAmb",count,mode5);
                Thread.sleep(10);
            } catch (InterruptedException ex) {
                Logger.getLogger(CrawlersMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        private int dispInfo(List<DSComposite> list,String title,int count,DefaultTableModel mode){
            String[] vals ;
//            System.out.println(title);
            for(int i=0;i<list.size();i++){
                vals = new String[16];
                vals[0] = count+"";
                count = count + 1;
                vals[1] = list.get(i).label;
                vals[2] = list.get(i).name;
                vals[3] = list.get(i).local.address;
                vals[4] = list.get(i).local.province;
                vals[5] = list.get(i).local.city;
                vals[6] = list.get(i).local.county;
                vals[7] = list.get(i).local.Road;
                vals[8] = list.get(i).local.RoadNo;
                vals[9] = list.get(i).local.township;
                vals[10] = list.get(i).local.village;
                vals[11] = list.get(i).local.building;
                vals[12] = list.get(i).local.floor;
                vals[13] = list.get(i).local.room;
                vals[14] = list.get(i).local.reference;
                vals[15] = list.get(i).local.stat+"";
                mode.addRow(vals);
            }
            return count;
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrawlersMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrawlersMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrawlersMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrawlersMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrawlersMain().setVisible(true);
            }
        });
    }
    
    private ParseWorkConfigXml config;
    private List<DSExtractor> params;
    private int currJobIndex = -1;
    MainServer server ;
    private Vector<String> listVals = new Vector<String>();
    
    private DispState disp = new DispState();
    DefaultTableModel mode3;
    DefaultTableModel mode4;
    DefaultTableModel mode5;
    
    
    class DispState implements Runnable{
        int state = 1;
        
        public synchronized void stopDisp(){
            state = 0;
        }
        
        public void run(){
            try {
                while(state == 1){
                    display();
                    Thread.sleep(1000);
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(CrawlersMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        public void display(){
            String[] header = { "名称", "值" }; //定义表头
            DefaultTableModel model=new DefaultTableModel(header,0);//用表头生成一个DefaultTableModel 对象
//            model.addRow(new String[]{"最大并发数",MainServer.state.crawlers + ""});
//            model.addRow(new String[]{"当前并发数",server.listCrawlers.size() + ""});
            int size = MainServer.DBCrawler.listCrawlerUrls.size();
            int sum = 0;
            for(int i=0;i<size;i++){
                int count = MainServer.DBCrawler.listCrawlerUrls.get(i).size();
                model.addRow(new String[]{ i + "层等待处理链接数",count+""});
                sum = sum + count;
            }
            model.addRow(new String[]{"链接处理状态",""});
            model.addRow(new String[]{"等待下载总数",sum +""});            
            model.addRow(new String[]{"已下载总数",MainServer.DBCrawler.mapDownload.size()+""});
//            model.addRow(new String[]{"重复链接数",MainServer.state.linkRepeat+""});
            
//            model.addRow(new String[]{"链接总数",MainServer.state.getLinkPageSum() + ""});
//            model.addRow(new String[]{"过滤链接数",MainServer.state.getLinkFilters() + ""});
            
            model.addRow(new String[]{"HTML网页内容处理状态",""});
//            model.addRow(new String[]{"并发数",server.listExtractors.size() + ""});   
            model.addRow(new String[]{"等待处理的html总数",MainServer.DBCrawler.listHtmlPages.size() + ""});            
//            model.addRow(new String[]{"处理html总数",MainServer.state.pageExtractNum + ""});            
            
//            model.addRow(new String[]{"特征库匹配成功数",MainServer.state.pageMacthNum + ""});            
//            model.addRow(new String[]{"特征库匹配不成功数",MainServer.state.pageNoMacthNum + ""});
//            model.addRow(new String[]{"可提取信息网页数",MainServer.state.pageContaintItems + ""});
            
            model.addRow(new String[]{"提取信息项总数",MainServer.DBCrawler.listDSComposites.size() + ""});
            
            
            model.addRow(new String[]{"地址解析统计", ""});
//            model.addRow(new String[]{"直接解析数",MainServer.state.itemCity + ""});
//            model.addRow(new String[]{"无法识别地址",MainServer.state.itemCityNull + ""});
//            model.addRow(new String[]{"歧义地址",MainServer.state.itemAmbiguity + ""});
            
            jTable2.setModel(model);
            
            jProgressBar1.setMaximum(sum+MainServer.DBCrawler.mapDownload.size());
            jProgressBar1.setMinimum(1);
            jProgressBar1.setValue(MainServer.DBCrawler.mapDownload.size());
            jProgressBar1.setStringPainted(true);
            jProgressBar1.setPreferredSize(new Dimension(300, 20));
            jProgressBar1.setBorderPainted(true);
            jProgressBar1.setBackground(Color.blue); 
            jProgressBar1.setVisible(true);
            
//            jTxtCrawlers.setText(server.listCrawlers.size()+"");
            jTxtUrlSum.setText(sum+MainServer.DBCrawler.mapDownload.size()+"");
            jTxtUrls.setText(MainServer.DBCrawler.mapDownload.size()+"");
            
            jProgressBar2.setMaximum(MainServer.DBCrawler.listHtmlPages.size() + MainServer.state.pageExtractNum);
            jProgressBar2.setMinimum(1);
            jProgressBar2.setValue(MainServer.state.pageExtractNum);
            jProgressBar2.setStringPainted(true);
            jProgressBar2.setPreferredSize(new Dimension(300, 20));
            jProgressBar2.setBorderPainted(true);
            jProgressBar2.setBackground(Color.blue); 
            jProgressBar2.setVisible(true); 
            jTxtPageSum.setText(MainServer.DBCrawler.listHtmlPages.size() + MainServer.state.pageExtractNum+"");
            jTxtPages.setText(MainServer.state.pageExtractNum+"");
            
            jProgressBar3.setMaximum(MainServer.DBCrawler.listDSComposites.size()); 
            jProgressBar3.setMinimum(1);
            jProgressBar3.setValue(MainServer.state.itemCity + MainServer.state.itemCityNull + MainServer.state.itemAmbiguity);
            jProgressBar3.setStringPainted(true);
            jProgressBar3.setPreferredSize(new Dimension(300, 20));
            jProgressBar3.setBorderPainted(true);
            jProgressBar3.setBackground(Color.blue); 
            jProgressBar3.setVisible(true); 
            jTxtItemSum.setText(MainServer.DBCrawler.listDSComposites.size()+"");
            jTxtItems.setText(MainServer.state.itemCity + MainServer.state.itemCityNull + MainServer.state.itemAmbiguity+"");            
            
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonContinue;
    private javax.swing.JButton jButtonInterupter;
    private javax.swing.JButton jButtonOutput;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTxtCrawlers;
    private javax.swing.JTextField jTxtItemSum;
    private javax.swing.JTextField jTxtItems;
    private javax.swing.JTextField jTxtPageSum;
    private javax.swing.JTextField jTxtPages;
    private javax.swing.JTextField jTxtUrlSum;
    private javax.swing.JTextField jTxtUrls;
    // End of variables declaration//GEN-END:variables
}
