/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package wuit.application.wins;

import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import wuit.crawler.database.PageFeaturesDB;

/**
 *
 * @author lxl
 */
public class PageClearConfig extends javax.swing.JFrame {

    /**
     * Creates new form PageClearConfig
     */
    public PageClearConfig() {
        initComponents();
        pageClear = new PageHtmlClear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonPageClearSave = new javax.swing.JButton();
        jButtonPageClearCancel = new javax.swing.JButton();
        jButtonPageClearAdd = new javax.swing.JButton();
        jButtonPageClearDel = new javax.swing.JButton();
        jButtonPageClearRefresh = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePageClear = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaPageClear = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setToolTipText("welcome");
        jPanel2.setName(""); // NOI18N

        jButtonPageClearSave.setText("保存");
        jButtonPageClearSave.setActionCommand("");
        jButtonPageClearSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPageClearSaveActionPerformed(evt);
            }
        });

        jButtonPageClearCancel.setText("返回");
        jButtonPageClearCancel.setToolTipText("退出系统");

        jButtonPageClearAdd.setText("添加");
        jButtonPageClearAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPageClearAddActionPerformed(evt);
            }
        });

        jButtonPageClearDel.setText("删除");
        jButtonPageClearDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPageClearDelActionPerformed(evt);
            }
        });

        jButtonPageClearRefresh.setText("刷新");
        jButtonPageClearRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPageClearRefreshActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("jRadioButton1");
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("jRadioButton2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButtonPageClearAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPageClearDel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPageClearSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPageClearRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPageClearCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPageClearSave)
                    .addComponent(jButtonPageClearCancel)
                    .addComponent(jButtonPageClearAdd)
                    .addComponent(jButtonPageClearDel)
                    .addComponent(jButtonPageClearRefresh)
                    .addComponent(jRadioButton1))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTablePageClear.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePageClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePageClearMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTablePageClear);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel4);

        jTextAreaPageClear.setColumns(20);
        jTextAreaPageClear.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextAreaPageClear.setRows(5);
        jScrollPane2.setViewportView(jTextAreaPageClear);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel5);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTablePageClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePageClearMouseClicked
        // TODO add your handling code here:
        int selRow = jTablePageClear.getSelectedRow();
//        if(feature.rowFeature>=0)
        pageClear.update();
        pageClear.rowClear = selRow;
        pageClear.setClearHtml();        
    }//GEN-LAST:event_jTablePageClearMouseClicked

    private void jButtonPageClearSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPageClearSaveActionPerformed
        // TODO add your handling code here:
        pageClear.save();
    }//GEN-LAST:event_jButtonPageClearSaveActionPerformed

    private void jButtonPageClearAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPageClearAddActionPerformed
        // TODO add your handling code here:
        pageClear.addnew();
    }//GEN-LAST:event_jButtonPageClearAddActionPerformed

    private void jButtonPageClearDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPageClearDelActionPerformed
        // TODO add your handling code here:
        pageClear.delete();
    }//GEN-LAST:event_jButtonPageClearDelActionPerformed

    private void jButtonPageClearRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPageClearRefreshActionPerformed
        // TODO add your handling code here:
        pageClear.refresh();
    }//GEN-LAST:event_jButtonPageClearRefreshActionPerformed

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageClearConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageClearConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageClearConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageClearConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageClearConfig().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonPageClearAdd;
    private javax.swing.JButton jButtonPageClearCancel;
    private javax.swing.JButton jButtonPageClearDel;
    private javax.swing.JButton jButtonPageClearRefresh;
    private javax.swing.JButton jButtonPageClearSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTablePageClear;
    private javax.swing.JTextArea jTextAreaPageClear;
    // End of variables declaration//GEN-END:variables

    PageHtmlClear pageClear ;

    /*
    class PageHtmlClear{
        JTable table;
        JTextArea txtAear;
        PageFeaturesDB db;
        List<PageClear> rs = new ArrayList<PageClear>();
        DefaultTableModel mode1 = null;  
        int rowClear = -1;
        
        public PageHtmlClear(JTable table,JTextArea txtAear){
            this.table = table;
            this.txtAear = txtAear;
            db = new PageFeaturesDB();
            db.SelectPageClear(rs);            
            InitTable();
            display( );
        }
        
        public void InitTable(){
            
            if(table == null)
                return;
            table.setRowHeight(24);
            String[] header = { "序号","名称"}; //定义表头
            mode1 = new DefaultTableModel(header,0){
                public boolean isCellEditable(int row, int column){
                    if(column==0)
                        return false;
                    else
                        return true;
                }
            };
            mode1.setColumnCount(2);
            table.setModel(mode1);
            table.getTableHeader().setFont(new Font("Dialog", 0, 14));         
            
            TableColumn Col0 = table.getColumnModel().getColumn(0);
            Col0.setPreferredWidth(40);            
            Col0.setMaxWidth(40);            

            TableColumn Col1 = table.getColumnModel().getColumn(0);
            Col1.setPreferredWidth(100);            
            Col1.setMaxWidth(400);
        }
        
        public void display( ){
            if(table == null || rs == null)
                return;
            while(mode1.getRowCount()>0){
                mode1.removeRow(0);
            }
            
            int rowNum = 0;
            for(int i=0; i<rs.size();i++){
                if(rs.get(i).state == 3)
                    continue;
                String[] row = {rowNum+"",rs.get(i).name};
                mode1.addRow(row);
                rowNum++;
            }
        } 
        
        public void refresh(){
            if(db == null)
                db = new PageFeaturesDB();
            if(rs == null)
                rs = new ArrayList<PageClear>();
            else
                rs.clear();
            db.SelectPageClear(rs);
            display();
            rowClear = -1;
        }        
        
        private int getRsIndex(){
           if(rowClear<0)
                return -1;
           int i = 0;
           int delRow = 0;
           while(i<=rowClear + delRow){
               if(rs.get(i).state == 3)
                   delRow++;
               i++;
           }
           return rowClear + delRow; 
        }        
        
        public void setClearHtml(){
           int row = getRsIndex();
           if(row<0)
               return;           
           jTextAreaPageClear.setText(rs.get(row).xml);
        }    
        
        public void addnew(){
            int id = rs.get(rs.size()-1).id + 1;
            String[] row = {id + "",""};
            mode1.addRow(row);
            
            PageClear info = new PageClear();
            info.id = id;
            info.name = "";
            info.state = 1;
            rs.add(info);
        }        
        
        public void update(){
           int row = getRsIndex();
           if(row<0)
               return;
           String name = (String)mode1.getValueAt(row,1);
           String xml = jTextAreaPageClear.getText();
           
           String _name = rs.get(row).name;
           String _xml = rs.get(row).xml;
           
           if(((_name != null && !_name.equals(name)) 
                   || (_xml != null && !_xml.equals(xml)))
                   && rs.get(row).state == 0 ){
                rs.get(row).state = 2;
            }
           
           rs.get(row).name = name;
           rs.get(row).xml = xml;           
        }        
        public void delete(){
            int row = getRsIndex();            
            if(row<0)
                return;            
            if(rs.get(row).state == 1)
                rs.remove(row);
            else
                rs.get(row).state = 3;
            display();
        }
        
        public void save(){
            if(rowClear>=0)
                update();
            for(int i=0; i<rs.size(); i++){
                PageClear _clear = new PageClear();                
                _clear.name = rs.get(i).name;
                _clear.xml = rs.get(i).xml;
                _clear.id = rs.get(i).id;
//                _feature.fields = rs.get(i).fields;
                if(rs.get(i).state == 1){                    
//                    db.InsertFeature(_feature);
                    rs.get(i).state = 0;
                    continue;
                }
                if(rs.get(i).state == 2){
                    db.UpdatePageClear(rs.get(i).xml, rs.get(i).name, rs.get(i).id);;
                    rs.get(i).state = 0;
                    continue;
                }
                if(rs.get(i).state == 3){
//                    db.DeleteFeature(_feature);
//                    rs.remove(i);
                    continue;
                }
            }
        }        
    }
    */
}
