/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package wuit.application.wins;

import java.awt.Color;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author lxl
 */
public class MainApp extends javax.swing.JFrame {

    /**
     * Creates new form MainApp
     */
    public MainApp() {
        initComponents();
        this.setLocation(300,100);
        InlitializeTree();
    }
    
    private void InlitializeTree(){
        
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("互联网位置信息采集");
//        addSubNode(mdl.id,root,list);
        DefaultMutableTreeNode nodeSearchMode = new DefaultMutableTreeNode("搜索配置");
        nodeSearchMode.add(new DefaultMutableTreeNode("垂直搜索"));
        nodeSearchMode.add(new DefaultMutableTreeNode("关键字搜索"));
        nodeSearchMode.add(new DefaultMutableTreeNode("直接搜索"));
        
        DefaultMutableTreeNode nodeSearchAddress = new DefaultMutableTreeNode("地名查询");
        
        DefaultMutableTreeNode nodeSearchLib = new DefaultMutableTreeNode("特征模板库");
        nodeSearchLib.add(new DefaultMutableTreeNode("网页清理"));
        nodeSearchLib.add(new DefaultMutableTreeNode("默认提取"));
        nodeSearchLib.add(new DefaultMutableTreeNode("网页特征库"));
        
        root.add(nodeSearchMode);
        root.add(nodeSearchLib);
        root.add(nodeSearchAddress);
        TreeModel treeModel = new DefaultTreeModel(root);
        jTreeMnue.setModel(treeModel);
    }    
   
    private void loadPageFeature(){
        PageFeature feature = new PageFeature();
        jTabPaneContent.addTab("网页特征", feature.panel1);
        feature.panel1.setBackground(Color.white);
        jTabPaneContent.setSelectedIndex(jTabPaneContent.getTabCount()-1);
        jTabPaneContent.setTabComponentAt(jTabPaneContent.getSelectedIndex(), new JTabbedPaneTitle(jTabPaneContent,"网页特征",feature));        
    }

    private void loadPageItems(){
        PageItems items = new PageItems();
        jTabPaneContent.addTab("默认提取", items.panel1);
        items.panel1.setBackground(Color.white);
        jTabPaneContent.setSelectedIndex(jTabPaneContent.getTabCount()-1);        
        jTabPaneContent.setTabComponentAt(jTabPaneContent.getSelectedIndex(), new JTabbedPaneTitle(jTabPaneContent,"默认提取",items));
    }    
    
    private void loadPageClearHtml(){
        PageHtmlClear items = new PageHtmlClear();        
        jTabPaneContent.addTab("网页清理", items.panel1);
        items.panel1.setBackground(Color.white);
        jTabPaneContent.setSelectedIndex(jTabPaneContent.getTabCount()-1);
        jTabPaneContent.setTabComponentAt(jTabPaneContent.getSelectedIndex(), new JTabbedPaneTitle(jTabPaneContent,"网页清理",items)); 
    }
    
    private void loadCrawlers(){
        PageCrawler pageCrawler0 = new PageCrawler(0);
        jTabPaneContent.addTab("垂直搜索", pageCrawler0.panel1);
        pageCrawler0.panel1.setBackground(Color.white);
        jTabPaneContent.setSelectedIndex(jTabPaneContent.getTabCount()-1);
        jTabPaneContent.setTabComponentAt(jTabPaneContent.getSelectedIndex(), new JTabbedPaneTitle(jTabPaneContent,"垂直搜索",pageCrawler0));
    }

    private void loadCrawlers1(){
//        jTabPaneContent.addTab("关键字搜索", jPanelCrawlers1);
//        jPanelCrawlers1.setBackground(Color.white);
//        int index = jTabPaneContent.getTabCount() - 1;
//        jTabPaneContent.setSelectedIndex(jTabPaneContent.getTabCount()-1); 
        
//        crawlerConfig.setCrawlerParams();
//        jTabPaneContent.setTabComponentAt(jTabPaneContent.getSelectedIndex(), new JTabbedPaneTitle(jTabPaneContent,"关键字搜索"));
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitle = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelMain = new javax.swing.JPanel();
        jSplitPaneMain = new javax.swing.JSplitPane();
        jPanelTree = new javax.swing.JPanel();
        jScrollPaneTree = new javax.swing.JScrollPane();
        jTreeMnue = new javax.swing.JTree();
        jPanelContent = new javax.swing.JPanel();
        jTabPaneContent = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanelTitle.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTitle.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("位置信息服务");

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTree.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelTree.setPreferredSize(new java.awt.Dimension(200, 412));

        jTreeMnue.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jTreeMnue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTreeMnueMouseClicked(evt);
            }
        });
        jScrollPaneTree.setViewportView(jTreeMnue);

        javax.swing.GroupLayout jPanelTreeLayout = new javax.swing.GroupLayout(jPanelTree);
        jPanelTree.setLayout(jPanelTreeLayout);
        jPanelTreeLayout.setHorizontalGroup(
            jPanelTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneTree, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
        );
        jPanelTreeLayout.setVerticalGroup(
            jPanelTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTreeLayout.createSequentialGroup()
                .addComponent(jScrollPaneTree, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jSplitPaneMain.setLeftComponent(jPanelTree);

        jPanelContent.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContent.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTabPaneContent.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabPaneContent.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jTabPaneContent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabPaneContentMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabPaneContent, javax.swing.GroupLayout.DEFAULT_SIZE, 1109, Short.MAX_VALUE)
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabPaneContent, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );

        jSplitPaneMain.setRightComponent(jPanelContent);

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneMain, javax.swing.GroupLayout.DEFAULT_SIZE, 1147, Short.MAX_VALUE)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneMain, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTreeMnueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTreeMnueMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            System.out.println(jTreeMnue.getSelectionPath());
            TreePath vals = jTreeMnue.getSelectionPath();            
            System.out.println(vals.getLastPathComponent());
            String val = (String)vals.getLastPathComponent().toString();
            if(val.equals("垂直搜索")){
                loadCrawlers();
            }
            if(val.equals("关键字搜索")){
                loadCrawlers1();
            }            
            if(val.equals("网页特征库")){
                loadPageFeature();
            }
            if(val.equals("网页清理")){
                loadPageClearHtml();
            }            
            if(val.equals("默认提取")){
                loadPageItems();
            }
        }        
    }//GEN-LAST:event_jTreeMnueMouseClicked

    private void jTabPaneContentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabPaneContentMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            int index  = jTabPaneContent.getSelectedIndex();
            jTabPaneContent.remove(index); 
        }
    }//GEN-LAST:event_jTabPaneContentMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JPanel jPanelTree;
    private javax.swing.JScrollPane jScrollPaneTree;
    private javax.swing.JSplitPane jSplitPaneMain;
    private javax.swing.JTabbedPane jTabPaneContent;
    private javax.swing.JTree jTreeMnue;
    // End of variables declaration//GEN-END:variables

}
